Documentation
aureliusenterprise/m4i_atlas_core pull request #4
Opened 2023-03-20 08:17 UTC by thijs-franck

2023-03-22 18:52 UTC, wombach requested changes
the fact that every file has been touched and every line has been adjusted, makes it impossible to see what all has changed! I do not know why this happened. Anyhow, I think it would be good to have in in config.sample.py and in credentials.sample.py a full list of options which are potentially used in library. Right now there are only the atlas credentials and the atlas server url, while in the documentation there are more options for keycloak.... potentially there are even more.

I see rst files in the code and I assume these have not been created manually. However, I do not see any documentatiuon on how the rst files have been created. Can you please add this part.

2023-03-22 18:52 UTC, wombach commented on scripts/config.sample.py
I think here should be a complete list of configurations which are possible in the lib. Best even provide a link to the md file where certain config parameters are explained

2023-03-22 18:52 UTC, wombach commented on scripts/credentials.sample.py
I think here should be a complete list of configurations which are possible in the lib. Best even provide a link to the md file where certain config parameters are explained

2023-03-22 18:52 UTC, wombach commented on README.md
> +| `keycloak.client.secret.key`    | True     | The public RS256 key associated with the Keycloak realm.                    |
it is important to state that the keycloak.client.secret.key key has to be defined, but can contain an arbitrary value since it is not checked in the default settings.

2023-03-22 18:52 UTC, wombach commented on README.md
> +| `keycloak.realm.name`           | True     | The name of the Keycloak realm.                                             |
Please add that the default realm name is m4i

2023-03-22 18:52 UTC, wombach commented on README.md
> +| `keycloak.client.id`            | True     | The name of the Keycloak client.                                            |
What is the default client ID we are using?

2023-03-22 18:52 UTC, wombach commented on README.md
> +| `keycloak.credentials.username` | False    | The username of the Keycloak user.                                          |
Default username is atlas

2023-03-22 18:52 UTC, wombach commented on README.md
> +| `keycloak.credentials.password` | False    | The password of the Keycloak user.                                          |
Passwords for standard users are usually auto generated and can be derived after deploying the Aurelius Atlas solution.

2023-03-22 18:52 UTC, wombach commented on README.md
> +
Which part of the configuration does where? STandard stuff to config.py, passwords and users to credentials.py.... doesn't really matter, but that's why we have the two classses

2023-03-22 18:52 UTC, wombach commented on README.md
> +
WHat are the requirements to actually run the pytest? 
Does a connection to atlas has to be configured? Anything else?
Does the pytest run at the moment?
Does it make sense to have a subset of the pytest which can be executed without a connection to atlas?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +
is it fair to say that all atlas functions require a set of config parameters. Can we call out the requiredconfig parameters here?
Maybe it is a good idea to point to the Apache Atlas documentation about the terms being used. Then people can look up what a glossary is etc. You are not explaining it and we should not explain it, but we have to point where the explanation can be found.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +
can we please make this a complete and executable example. This is applies to all functions in this readme file

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +
In the standard Aurelius Atlas configuration, each delete has been configured to be a hard delete. Thus, even using a soft delete API call, most likely ends up in a hard delete.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +
for me it would make sense to order the functions by their entity, thus first have all entity related functions, then all relations, then gloassry functions then classification fucntions etc...

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +You can access the cache for any API function through the `cache` property. Here's an example of how to access the cache for the `get_entity_by_guid` function:
Why would you do this? What is the benefit?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +#### Clearing the cache
I would propose to merge this section with the previous one and keep the title clearing the cache. The you can keep pretty much the text, but then it is clear why you want to access the cache object.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +The `auth` submodule provides functionality for retrieving authentication tokens from Keycloak, which are required for accessing the Apache Atlas API.
In a different part of the documentaiton you differentiated between the standard Aurelius Atlas config with keycloak and the default apache atlas config with basic auth. I think this clarification is also required here.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +The `access_token` can then be used to authenticate requests to the Apache Atlas API.
Is it important to point out that an access token has a time to life and will expire at a certain moment?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +access_token = get_keycloak_token()
Point to the next section for config params

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/api/README.md
> +| ------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------
I made quite some comments on a similar part in the top level readme. Please default values for the different params. Please indicate which property goes into config and credentials.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/config/README.md
> +The ConfigStore raises a `MissingRequiredConfigException` when a required key is not found and no default value has been provided. This exception can be caught and handled as needed in your applicati
What happens if a non-required key is requested, which is not defined in the store? Is there an exception? Or is there a None value provided?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/entities/atlas/README.md
> +Each data object is a `dataclass` and is designed to be easily serialized and deserialized using the `dataclasses_json` library. This allows for convenient conversion between JSON and the correspondi
Can you please add a reference to some documentation about python dataclasses.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/entities/atlas/README.md
> +In the given example, the `key` attribute is not explicitly defined as part of the schema for `BusinessDataDomain`. In such cases, the attributes field of the resulting instance will include an `unma
This gives the flexibility to add all kind of additional properties to the entity.

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/entities/atlas/README.md
> +In this example, the `Entity` data object from the library is used to validate the `input_data` JSON using its associated Marshmallow schema. If the data is valid, the `validate` method will not retu
In this concrete example: what is the outcome? Is it a valid schema? Do you get indications where the schema is wrong?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/entities/atlas/README.md
> +from m4i_atlas_core import Entity
Does this code fragment work and if so what is the output?

2023-03-22 18:52 UTC, wombach commented on m4i_atlas_core/entities/atlas/README.md
> +
Are these type definitions used somewhere in our code? Why do you want to use them?

2023-03-23 06:22 UTC, thijs-franck commented on README.md
> +| `keycloak.client.secret.key`    | True     | The public RS256 key associated with the Keycloak realm.                    |
Is this really true?

2023-03-23 06:28 UTC, thijs-franck commented on README.md
> +
Yes pytest is working. No we do not need a connection to atlas. The whole point of having unit tests is that they can run independently to test the application logic. If a function depends on some integration, it should be mocked as part of the unit test.

We do not include any integration tests at the moment.

2023-03-23 06:32 UTC, thijs-franck commented on m4i_atlas_core/api/README.md
> +
I was not aware of this. Does it make sense to have a `delete_entity_soft` and `delete_entity_hard` function then? Or should we consolidate the current soft delete into a single `delete_entity` function and remove the function for the admin api?

2023-03-23 09:09 UTC, wombach commented on README.md
> +
I pulled the current version from the git into a new virtual environment running python 3.10 and tried to run pytest and for me 5 tests failed. But maybe we have to look at this afterwards

2023-03-23 09:09 UTC, wombach commented on m4i_atlas_core/api/README.md
> +
In my opinion it still makes sense, because people may decide to re-configure Apache Atlas to use soft deletes anyhow.

2023-03-23 14:39 UTC, thijs-franck commented on README.md
> +| `keycloak.credentials.password` | False    | The password of the Keycloak user.                                          |
Added a note below

2023-03-23 14:41 UTC, thijs-franck commented on README.md
> +
We mostly have the two files so that when you are screen sharing, you can show your config file wihout showing any secrets/password. There is no real technical reason why we have two files, it could just be the one.

We also do not strictly need to store config values in files at all. You could also load them from the environment with some additional scripting to init the config store.

2023-03-23 14:44 UTC, thijs-franck commented on README.md
> +| `keycloak.credentials.username` | False    | The username of the Keycloak user.                                          |
Should we be encouraging the use of default credentials?

2023-03-23 14:44 UTC, thijs-franck commented on README.md
> +| `keycloak.realm.name`           | True     | The name of the Keycloak realm.                                             |
Added

2023-03-23 14:44 UTC, thijs-franck commented on README.md
> +| `keycloak.client.id`            | True     | The name of the Keycloak client.                                            |
I don't know.

2023-03-23 14:46 UTC, thijs-franck commented on README.md
> +
So pytest is working, just not the actual tests 😜

But yes, let's have a look to see if we can fix/add some more test after we merge this.

2023-03-23 18:33 UTC, wombach commented on README.md
> +| `keycloak.client.secret.key`    | True     | The public RS256 key associated with the Keycloak realm.                    |
yes

2023-03-23 18:35 UTC, wombach commented on README.md
> +| `keycloak.client.id`            | True     | The name of the Keycloak client.                                            |
it should be m4i_atlas

2023-03-23 18:36 UTC, wombach commented on README.md
> +| `keycloak.credentials.username` | False    | The username of the Keycloak user.                                          |
teh default credentials are randomly generated credentials; they are not hard coded values like admin/admin

2023-03-23 18:37 UTC, wombach commented on README.md
> +
So if we do not advocate to do it this way, why do we have this pattern in all libs? I suggest to propose this pattern such that users also understand why we made this separation.

2023-03-23 19:47 UTC, thijs-franck commented on README.md
> +| `keycloak.credentials.username` | False    | The username of the Keycloak user.                                          |
Is this also the case for basic/Apache Atlas authentication?

2023-03-24 10:58 UTC, wombach commented on README.md
> +| `keycloak.credentials.username` | False    | The username of the Keycloak user.                                          |
no. In Apache Atlas the default admin password is admin. In Aurelius Atlas the default passwords are randomly generated passwords, which will change with every deployment - this is default behavior of the deployment of Aurelius Atlas.

2023-03-24 11:30 UTC, merged